name: rapid_api_explorer
description: A Postman-like REST/GraphQL client built with Flutter.
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.3.2
  flutter_riverpod: ^2.3.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_highlight: ^0.8.2
  go_router: ^6.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
